runtime: python39
entrypoint: uvicorn kotatsu.app:app --port $PORT --workers 2

instance_class: F1
automatic_scaling:
  min_idle_instances: 1

inbound_services:
  - warmup

handlers:
  - url: /slack/events
    secure: always
    script: auto

includes:
  - secret.yaml
